import DeviceStatus from '../interfaces/DeviceStatus';

export const mockDeviceStatus: DeviceStatus[] = [
    {
        Address: '1',
        Maintained: false,
        BatteryCharging: false,
        BatteryTestRunning: false,
        LampTestRunning: false,
        BatteryCapacityFault: false,
        LampFault: false,
        ChargerFault: false,
        MainsFault: false,
        BatteryVoltage: '12.5',
        ChargeCurrent: '0.5',
        LampCurrent: '0.5',
        Autonomy: '2',
        Version: '1.0',
        LuminaryModel: 'Luminary 1',
        BatteryFault: false,
        BatteryCutOffStatus: false,
        SpiCommError: false,
        ResolvedSpiCommError: false,
        ModuleVersion: '1.0',
        ModuleType: 1,
        TimeToSend: '12:00',
        HasWrongLuminaireType: false,
        FullyCharged: false,
        Rfchannel: '1',
        LampTestMade: false,
        DimmingLevel: '50',
        Zone: 1,
        SidToGo: '1',
        NetworkidToGo: '1',
        RfchannelToGo: 1,
        InForcedEmergency: false,
        Rssi: 1,
        RssiWithUnit: '1',
        NetworkLevel: '1',
        HopCounter: '1',
        MessageCounter: '1',
        LatencyCounter: '1',
        Rc1181fwVersion: '1.0',
    },
    {
        Address: '2',
        Maintained: false,
        BatteryCharging: false,
        BatteryTestRunning: false,
        LampTestRunning: false,
        BatteryCapacityFault: false,
        LampFault: false,
        ChargerFault: false,
        MainsFault: false,
        BatteryVoltage: '12.5',
        ChargeCurrent: '0.5',
        LampCurrent: '0.5',
        Autonomy: '2',
        Version: '1.0',
        LuminaryModel: 'Luminary 2',
        BatteryFault: false,
        BatteryCutOffStatus: false,
        SpiCommError: false,
        ResolvedSpiCommError: false,
        ModuleVersion: '1.0',
        ModuleType: 1,
        TimeToSend: '12:00',
        HasWrongLuminaireType: false,
        FullyCharged: false,
        Rfchannel: '1',
        LampTestMade: false,
        DimmingLevel: '50',
        Zone: 1,
        SidToGo: '1',
        NetworkidToGo: '1',
        RfchannelToGo: 1,
        InForcedEmergency: false,
        Rssi: 1,
        RssiWithUnit: '1',
        NetworkLevel: '1',
        HopCounter: '1',
        MessageCounter: '1',
        LatencyCounter: '1',
        Rc1181fwVersion: '1.0',
    },
    {
        Address: '3',
        Maintained: false,
        BatteryCharging: false,
        BatteryTestRunning: false,
        LampTestRunning: false,
        BatteryCapacityFault: false,
        LampFault: false,
        ChargerFault: false,
        MainsFault: false,
        BatteryVoltage: '12.5',
        ChargeCurrent: '0.5',
        LampCurrent: '0.5',
        Autonomy: '2',
        Version: '1.0',
        LuminaryModel: 'Luminary 3',
        BatteryFault: false,
        BatteryCutOffStatus: false,
        SpiCommError: false,
        ResolvedSpiCommError: false,
        ModuleVersion: '1.0',
        ModuleType: 1,
        TimeToSend: '12:00',
        HasWrongLuminaireType: false,
        FullyCharged: false,
        Rfchannel: '1',
        LampTestMade: false,
        DimmingLevel: '50',
        Zone: 1,
        SidToGo: '1',
        NetworkidToGo: '1',
        RfchannelToGo: 1,
        InForcedEmergency: false,
        Rssi: 1,
        RssiWithUnit: '1',
        NetworkLevel: '1',
        HopCounter: '1',
        MessageCounter: '1',
        LatencyCounter: '1',
        Rc1181fwVersion: '1.0',
    },
];
