import { LuminareModel } from "../interfaces/Luminaire";

export const mockLuminaires: LuminareModel[] = [
    {
        uid: 1,
        address: 123456789,
        maintained: 1,
        batteryCharging: 1,
        batteryTestRunning: 0,
        lampTestRunning: 0,
        batteryCapacityFault: 0,
        lampFault: 1,
        chargerFault: 0,
        mainsFault: 0,
        batteryVoltage: "12.6V",
        chargeCurrent: "1.2A",
        lampCurrent: "0.8A",
        autonomy: "2 hours",
        version: "1.0.0",
        luminaryModel: "Model A",
        batteryFault: 0,
        batteryCutOffStatus: 0,
        spiCommError: 0,
        resolvedSpiCommError: 1,
        moduleVersion: "2.1.0",
        moduleType: 1,
        timeToSend: "2024-06-29 12:00:00",
        hasWrongLuminaireType: 0,
        fullyCharged: 1,
        rfchannel: 11,
        lampTestMade: 1,
        dimmingLevel: "50%",
        zone: 1,
        sidToGo: 987654321,
        networkidToGo: 192837465,
        rfchannelToGo: 12,
        inForcedEmergency: 0,
        rssi: -70,
        rssiWithUnit: "-70 dBm",
        networkLevel: 2,
        hopCounter: 1,
        messageCounter: 100,
        latencyCounter: 20,
        rc1181fwVersion: "3.5.1",
        createdOn: new Date(),
        updateOn: new Date(),
    },
    {
        uid: 2,
        address: 223344556,
        maintained: 0,
        batteryCharging: 0,
        batteryTestRunning: 1,
        lampTestRunning: 0,
        batteryCapacityFault: 1,
        lampFault: 0,
        chargerFault: 1,
        mainsFault: 0,
        batteryVoltage: "11.9V",
        chargeCurrent: "0.9A",
        lampCurrent: "0.6A",
        autonomy: "1.5 hours",
        version: "1.1.0",
        luminaryModel: "Model B",
        batteryFault: 1,
        batteryCutOffStatus: 1,
        spiCommError: 1,
        resolvedSpiCommError: 0,
        moduleVersion: "2.2.0",
        moduleType: 2,
        timeToSend: "2024-06-30 13:00:00",
        hasWrongLuminaireType: 0,
        fullyCharged: 0,
        rfchannel: 15,
        lampTestMade: 0,
        dimmingLevel: "70%",
        zone: 2,
        sidToGo: 876543210,
        networkidToGo: 198765432,
        rfchannelToGo: 14,
        inForcedEmergency: 1,
        rssi: -65,
        rssiWithUnit: "-65 dBm",
        networkLevel: 3,
        hopCounter: 2,
        messageCounter: 200,
        latencyCounter: 30,
        rc1181fwVersion: "3.5.2",
        createdOn: new Date(),
        updateOn: new Date(),
    },
    {
        uid: 3,
        address: 334455667,
        maintained: 1,
        batteryCharging: 0,
        batteryTestRunning: 0,
        lampTestRunning: 1,
        batteryCapacityFault: 0,
        lampFault: 0,
        chargerFault: 0,
        mainsFault: 1,
        batteryVoltage: "12.0V",
        chargeCurrent: "1.0A",
        lampCurrent: "0.7A",
        autonomy: "2.5 hours",
        version: "1.2.0",
        luminaryModel: "Model C",
        batteryFault: 0,
        batteryCutOffStatus: 0,
        spiCommError: 0,
        resolvedSpiCommError: 1,
        moduleVersion: "2.3.0",
        moduleType: 3,
        timeToSend: "2024-07-01 14:00:00",
        hasWrongLuminaireType: 1,
        fullyCharged: 1,
        rfchannel: 20,
        lampTestMade: 1,
        dimmingLevel: "60%",
        zone: 3,
        sidToGo: 765432109,
        networkidToGo: 123456789,
        rfchannelToGo: 16,
        inForcedEmergency: 0,
        rssi: -60,
        rssiWithUnit: "-60 dBm",
        networkLevel: 4,
        hopCounter: 3,
        messageCounter: 300,
        latencyCounter: 25,
        rc1181fwVersion: "3.5.3",
        createdOn: new Date(),
        updateOn: new Date(),
    },
];
