import { LuminaireModel } from "../interfaces/Luminaire";

export const mockLuminaires: LuminaireModel[] = [
    {
        address: 123456789234,
        maintained: 1,
        batteryCharging: 1,
        batteryTestRunning: 0,
        lampTestRunning: 0,
        batteryCapacityFault: 0,
        lampFault: 1,
        chargerFault: 0,
        mainsFault: 0,
        batteryVoltage: "12.6V",
        chargeCurrent: "1.2A",
        lampCurrent: "0.8A",
        autonomy: "2 hours",
        version: "1.0.0",
        luminaryModel: "Model A",
        batteryFault: 0,
        batteryCutOffStatus: 0,
        spiCommError: 0,
        resolvedSpiCommError: 1,
        moduleVersion: "2.1.0",
        moduleType: 1,
        timeToSend: "2024-06-29 12:00:00",
        hasWrongLuminaireType: 0,
        fullyCharged: 1,
        rfchannel: 11,
        lampTestMade: 1,
        dimmingLevel: "50%",
        zone: 1,
        sidToGo: 987654321,
        networkidToGo: 192837465,
        rfchannelToGo: 12,
        inForcedEmergency: 0,
        rssi: -70,
        rssiWithUnit: "-70 dBm",
        networkLevel: 2,
        hopCounter: 1,
        messageCounter: 100,
        latencyCounter: 20,
        rc1181fwVersion: "3.5.1",
        createdOn: new Date(
            Date.now() -
                24 * 60 * 60 * 1000 * (Math.floor(Math.random() * 2) + 1)
        ),
        updateOn: new Date(),
    },
    {
        address: 223344556435435,
        maintained: 0,
        batteryCharging: 0,
        batteryTestRunning: 1,
        lampTestRunning: 0,
        batteryCapacityFault: 1,
        lampFault: 0,
        chargerFault: 1,
        mainsFault: 0,
        batteryVoltage: "11.9V",
        chargeCurrent: "0.9A",
        lampCurrent: "0.6A",
        autonomy: "1.5 hours",
        version: "1.1.0",
        luminaryModel: "Model B",
        batteryFault: 1,
        batteryCutOffStatus: 1,
        spiCommError: 1,
        resolvedSpiCommError: 0,
        moduleVersion: "2.2.0",
        moduleType: 2,
        timeToSend: "2024-06-30 13:00:00",
        hasWrongLuminaireType: 0,
        fullyCharged: 0,
        rfchannel: 15,
        lampTestMade: 0,
        dimmingLevel: "70%",
        zone: 2,
        sidToGo: 876543210,
        networkidToGo: 198765432,
        rfchannelToGo: 14,
        inForcedEmergency: 1,
        rssi: -65,
        rssiWithUnit: "-65 dBm",
        networkLevel: 3,
        hopCounter: 2,
        messageCounter: 200,
        latencyCounter: 30,
        rc1181fwVersion: "3.5.2",
        createdOn: new Date(
            Date.now() -
                24 * 60 * 60 * 1000 * (Math.floor(Math.random() * 2) + 1)
        ),
        updateOn: new Date(),
    },
    {
        address: 334455667564,
        maintained: 1,
        batteryCharging: 0,
        batteryTestRunning: 0,
        lampTestRunning: 1,
        batteryCapacityFault: 0,
        lampFault: 0,
        chargerFault: 0,
        mainsFault: 1,
        batteryVoltage: "12.0V",
        chargeCurrent: "1.0A",
        lampCurrent: "0.7A",
        autonomy: "2.5 hours",
        version: "1.2.0",
        luminaryModel: "Model C",
        batteryFault: 0,
        batteryCutOffStatus: 0,
        spiCommError: 0,
        resolvedSpiCommError: 1,
        moduleVersion: "2.3.0",
        moduleType: 3,
        timeToSend: "2024-07-01 14:00:00",
        hasWrongLuminaireType: 1,
        fullyCharged: 1,
        rfchannel: 20,
        lampTestMade: 1,
        dimmingLevel: "60%",
        zone: 3,
        sidToGo: 765432109,
        networkidToGo: 123456789,
        rfchannelToGo: 16,
        inForcedEmergency: 0,
        rssi: -60,
        rssiWithUnit: "-60 dBm",
        networkLevel: 4,
        hopCounter: 3,
        messageCounter: 300,
        latencyCounter: 25,
        rc1181fwVersion: "3.5.3",
        createdOn: new Date(
            Date.now() -
                24 * 60 * 60 * 1000 * (Math.floor(Math.random() * 2) + 1)
        ),
        updateOn: new Date(),
    },
    {
        address: 112233445454356,
        maintained: 0,
        batteryCharging: 1,
        batteryTestRunning: 0,
        lampTestRunning: 0,
        batteryCapacityFault: 1,
        lampFault: 0,
        chargerFault: 0,
        mainsFault: 0,
        batteryVoltage: "11.5V",
        chargeCurrent: "0.8A",
        lampCurrent: "0.5A",
        autonomy: "2.0 hours",
        version: "1.1.5",
        luminaryModel: "Model B",
        batteryFault: 0,
        batteryCutOffStatus: 0,
        spiCommError: 0,
        resolvedSpiCommError: 1,
        moduleVersion: "2.2.1",
        moduleType: 2,
        timeToSend: "2024-07-01 15:00:00",
        hasWrongLuminaireType: 0,
        fullyCharged: 0,
        rfchannel: 21,
        lampTestMade: 1,
        dimmingLevel: "70%",
        zone: 2,
        sidToGo: 987654321,
        networkidToGo: 987654321,
        rfchannelToGo: 17,
        inForcedEmergency: 1,
        rssi: -55,
        rssiWithUnit: "-55 dBm",
        networkLevel: 3,
        hopCounter: 2,
        messageCounter: 450,
        latencyCounter: 30,
        rc1181fwVersion: "3.4.2",
        createdOn: new Date(
            Date.now() -
                24 * 60 * 60 * 1000 * (Math.floor(Math.random() * 2) + 1)
        ),
        updateOn: new Date(),
    },
    {
        address: 2233445567653,
        maintained: 1,
        batteryCharging: 0,
        batteryTestRunning: 0,
        lampTestRunning: 1,
        batteryCapacityFault: 0,
        lampFault: 0,
        chargerFault: 0,
        mainsFault: 0,
        batteryVoltage: "12.3V",
        chargeCurrent: "1.2A",
        lampCurrent: "0.6A",
        autonomy: "3.0 hours",
        version: "1.3.0",
        luminaryModel: "Model D",
        batteryFault: 0,
        batteryCutOffStatus: 0,
        spiCommError: 0,
        resolvedSpiCommError: 1,
        moduleVersion: "2.4.0",
        moduleType: 4,
        timeToSend: "2024-07-01 16:00:00",
        hasWrongLuminaireType: 0,
        fullyCharged: 1,
        rfchannel: 22,
        lampTestMade: 0,
        dimmingLevel: "50%",
        zone: 1,
        sidToGo: 654321987,
        networkidToGo: 654321987,
        rfchannelToGo: 18,
        inForcedEmergency: 0,
        rssi: -65,
        rssiWithUnit: "-65 dBm",
        networkLevel: 5,
        hopCounter: 1,
        messageCounter: 500,
        latencyCounter: 20,
        rc1181fwVersion: "3.6.0",
        createdOn: new Date(
            Date.now() -
                24 * 60 * 60 * 1000 * (Math.floor(Math.random() * 2) + 1)
        ),
        updateOn: new Date(),
    },
    {
        address: 44556677823466,
        maintained: 1,
        batteryCharging: 1,
        batteryTestRunning: 1,
        lampTestRunning: 0,
        batteryCapacityFault: 0,
        lampFault: 1,
        chargerFault: 1,
        mainsFault: 0,
        batteryVoltage: "11.0V",
        chargeCurrent: "0.6A",
        lampCurrent: "0.4A",
        autonomy: "1.5 hours",
        version: "1.0.9",
        luminaryModel: "Model A",
        batteryFault: 0,
        batteryCutOffStatus: 0,
        spiCommError: 0,
        resolvedSpiCommError: 1,
        moduleVersion: "2.1.5",
        moduleType: 1,
        timeToSend: "2024-07-01 17:00:00",
        hasWrongLuminaireType: 0,
        fullyCharged: 0,
        rfchannel: 23,
        lampTestMade: 1,
        dimmingLevel: "40%",
        zone: 4,
        sidToGo: 123456098,
        networkidToGo: 123456098,
        rfchannelToGo: 19,
        inForcedEmergency: 1,
        rssi: -70,
        rssiWithUnit: "-70 dBm",
        networkLevel: 2,
        hopCounter: 4,
        messageCounter: 350,
        latencyCounter: 35,
        rc1181fwVersion: "3.3.1",
        createdOn: new Date(
            Date.now() -
                24 * 60 * 60 * 1000 * (Math.floor(Math.random() * 2) + 1)
        ),
        updateOn: new Date(Date.now() - 2 * 60 * 60 * 1000),
    },
    {
        address: 55667788976743,
        maintained: 0,
        batteryCharging: 0,
        batteryTestRunning: 0,
        lampTestRunning: 0,
        batteryCapacityFault: 0,
        lampFault: 0,
        chargerFault: 0,
        mainsFault: 0,
        batteryVoltage: "12.5V",
        chargeCurrent: "1.5A",
        lampCurrent: "0.9A",
        autonomy: "3.5 hours",
        version: "1.4.1",
        luminaryModel: "Model E",
        batteryFault: 0,
        batteryCutOffStatus: 0,
        spiCommError: 0,
        resolvedSpiCommError: 0,
        moduleVersion: "2.5.2",
        moduleType: 5,
        timeToSend: "2024-07-01 18:00:00",
        hasWrongLuminaireType: 0,
        fullyCharged: 1,
        rfchannel: 24,
        lampTestMade: 0,
        dimmingLevel: "80%",
        zone: 5,
        sidToGo: 321654987,
        networkidToGo: 321654987,
        rfchannelToGo: 20,
        inForcedEmergency: 0,
        rssi: -50,
        rssiWithUnit: "-50 dBm",
        networkLevel: 4,
        hopCounter: 3,
        messageCounter: 600,
        latencyCounter: 40,
        rc1181fwVersion: "3.7.1",
        createdOn: new Date(
            Date.now() -
                24 * 60 * 60 * 1000 * (Math.floor(Math.random() * 2) + 1)
        ),
        updateOn: new Date(),
    },
    {
        address: 6677889901235345,
        maintained: 1,
        batteryCharging: 0,
        batteryTestRunning: 1,
        lampTestRunning: 0,
        batteryCapacityFault: 1,
        lampFault: 0,
        chargerFault: 0,
        mainsFault: 1,
        batteryVoltage: "11.2V",
        chargeCurrent: "0.7A",
        lampCurrent: "0.6A",
        autonomy: "1.8 hours",
        version: "1.2.3",
        luminaryModel: "Model F",
        batteryFault: 1,
        batteryCutOffStatus: 1,
        spiCommError: 1,
        resolvedSpiCommError: 0,
        moduleVersion: "2.6.3",
        moduleType: 6,
        timeToSend: "2024-07-01 19:00:00",
        hasWrongLuminaireType: 1,
        fullyCharged: 0,
        rfchannel: 25,
        lampTestMade: 1,
        dimmingLevel: "90%",
        zone: 6,
        sidToGo: 987123456,
        networkidToGo: 987123456,
        rfchannelToGo: 21,
        inForcedEmergency: 1,
        rssi: -75,
        rssiWithUnit: "-75 dBm",
        networkLevel: 1,
        hopCounter: 5,
        messageCounter: 700,
        latencyCounter: 45,
        rc1181fwVersion: "3.8.2",
        createdOn: new Date(
            Date.now() -
                24 * 60 * 60 * 1000 * (Math.floor(Math.random() * 2) + 1)
        ),
        updateOn: new Date(Date.now() - 2 * 60 * 60 * 1000),
    },
];
