interface DeviceStatus {
    Address: string;
    Maintained: boolean;
    BatteryCharging: boolean;
    BatteryTestRunning: boolean;
    LampTestRunning: boolean;
    BatteryCapacityFault: boolean;
    LampFault: boolean;
    ChargerFault: boolean;
    MainsFault: boolean;
    BatteryVoltage: string;
    ChargeCurrent: string;
    LampCurrent: string;
    Autonomy: string;
    Version: string;
    LuminaryModel: string;
    BatteryFault: boolean;
    BatteryCutOffStatus: boolean;
    SpiCommError: boolean;
    ResolvedSpiCommError: boolean;
    ModuleVersion: string;
    ModuleType: number;
    TimeToSend: string;
    HasWrongLuminaireType: boolean;
    FullyCharged: boolean;
    Rfchannel: string;
    LampTestMade: boolean;
    DimmingLevel: string;
    Zone: number;
    SidToGo: string;
    NetworkidToGo: string;
    RfchannelToGo: number;
    InForcedEmergency: boolean;
    Rssi: number;
    RssiWithUnit: string;
    NetworkLevel: string;
    HopCounter: string;
    MessageCounter: string;
    LatencyCounter: string;
    Rc1181fwVersion: string;
}

export default DeviceStatus;
